apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environmentPrefix }}-{{ .Values.appName }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.environmentPrefix }}-{{ .Values.appName }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: {{ .Values.service.ports.protocol }}
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}